import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFile, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { join, resolve, sep } from 'node:path';
import { tmpdir } from 'node:os';
import { downloadVideo, MAX_MEDIA_BYTES } from './download';

export const AI_METADATA = 'AI generated by 2049出片';
export interface RenderSettings { resolution: '480p' | '720p'; aspectRatio: '9:16' | '16:9' | '1:1'; durationSec: 5 }
export function runMediaTool(command: string, args: string[], cwd: string): Promise<string> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, { cwd, windowsHide: true,
      env: { PATH: process.env.PATH, SystemRoot: process.env.SystemRoot, TEMP: process.env.TEMP } });
    let stdout = '';
    const timer = setTimeout(() => { child.kill('SIGKILL'); }, command === 'ffprobe' ? 30000 : 120000);
    child.stdout.on('data', chunk => { stdout += String(chunk); if (stdout.length > 65536) child.kill('SIGKILL'); });
    child.stderr.resume();
    child.on('error', () => { clearTimeout(timer); reject(new Error('Media executable unavailable')); });
    child.on('close', code => { clearTimeout(timer); if (code === 0) resolvePromise(stdout); else reject(new Error('Media processing failed')); });
  });
}
async function probe(file: string, cwd: string) {
  const parsed = JSON.parse(await runMediaTool('ffprobe', ['-v', 'error', '-f', 'mov', '-show_entries',
    'format=duration:format_tags=comment:stream=codec_type,width,height', '-of', 'json', file], cwd));
  const video = parsed.streams?.find((stream: { codec_type: string }) => stream.codec_type === 'video');
  const durationMs = Math.round(Number(parsed.format?.duration) * 1000);
  if (!video || !Number.isInteger(durationMs) || durationMs < 500 || durationMs > 7000 ||
      !Number.isInteger(video.width) || !Number.isInteger(video.height) || video.width < 16 || video.height < 16 || video.width > 4096 || video.height > 4096) throw new Error('Media dimensions or duration rejected');
  return { width: video.width as number, height: video.height as number, durationMs, comment: parsed.format.tags?.comment };
}
/** The caller owns the source path; this function copies it into an exclusive work directory. */
export async function renderVideo(source: string, settings: RenderSettings, fontFile: string, remote = true) {
  const directory = await mkdtemp(join(tmpdir(), 'wb-media-'));
  const parent = resolve(tmpdir()) + sep;
  if (!resolve(directory).startsWith(parent) || !directory.includes('wb-media-')) throw new Error('Temporary media path mismatch');
  try {
    if (remote) await downloadVideo(source, join(directory, 'source.mp4'));
    else await copyFile(source, join(directory, 'source.mp4'));
    if ((await stat(join(directory, 'source.mp4'))).size > MAX_MEDIA_BYTES) throw new Error('Media size limit exceeded');
    const original = await probe('source.mp4', directory);
    const [wide, high] = settings.aspectRatio.split(':').map(Number);
    if (Math.abs((original.width / original.height) / (wide / high) - 1) > 0.08) throw new Error('Provider aspect ratio mismatch');
    await copyFile(fontFile, join(directory, 'font.ttf'));
    await writeFile(join(directory, 'label.txt'), 'AI生成 · 2049出片', 'utf8');
    const edge = settings.resolution === '480p' ? 480 : 720;
    const scale = wide < high ? `${edge}:-2` : `-2:${edge}`;
    await runMediaTool('ffmpeg', ['-nostdin', '-y', '-protocol_whitelist', 'file,pipe', '-threads', '1', '-f', 'mov', '-enable_drefs', '0', '-i', 'source.mp4',
      '-map', '0:v:0', '-map', '0:a?', '-map_metadata', '-1', '-vf', `scale=${scale},drawtext=fontfile=font.ttf:textfile=label.txt:expansion=none:fontsize=24:fontcolor=white:box=1:boxcolor=black@0.5:boxborderw=8:x=w-tw-16:y=h-th-16`,
      '-c:v', 'libx264', '-preset', 'veryfast', '-threads', '1', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-metadata', `comment=${AI_METADATA}`,
      '-movflags', '+faststart+use_metadata_tags', '-fs', String(MAX_MEDIA_BYTES), 'output.mp4'], directory);
    const output = await probe('output.mp4', directory);
    if (output.comment !== AI_METADATA || Math.abs(output.durationMs - original.durationMs) > 250) throw new Error('Media output verification failed');
    const bytes = await readFile(join(directory, 'output.mp4'));
    if (bytes.length === 0 || bytes.length > MAX_MEDIA_BYTES) throw new Error('Media output size rejected');
    return { bytes, sha256: createHash('sha256').update(bytes).digest('hex'), width: output.width, height: output.height, durationMs: output.durationMs };
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}
